export default {
  LOGIN      : () => `/adminLogin`,
  REGISTER   : () => ``,
  FORGOT     : () => ``,
  LOGOUT     : () => `/adminLogout`,
  REFRESH_TOKEN :() => `/refreshToken`,
  RESET_PASSWORD : () => `/adminResetPassword`,
  ADMIN_CREATE_AREA :()=>`/createArea`,
  GET_AREAS: ()=>`/getAreas`,
  DELETE_AREA: ()=>`/deleteArea`,
  TOGGLE_AREA_ACTIVE: ()=>`/toggleAreaActive`,
  UPDATE_AREA: ()=>`/updateArea`,
  GET_ALL_COUPONS: ()=>`/getAllCoupons`,
  CREATE_COUPON: ()=>`/createCoupon`,
  TOGGLE_COUPON_STATUS: ()=>'',
  DELETE_COUPON: ()=>`/deleteCoupon`,
  UPDATE_COUPON: ()=>`updateCoupon`,
  GET_ALL_PRODUCTS: ()=>`/getAllProducts`,
  GET_PROFILE: ()=>`/getAdminProfile`,
  UPDATE_PHONE_NUMBER: ()=>`/adminUpdatePhoneNumber`,
  UPDATE_PASSWORD: ()=>`/adminChangePassword`,
};